# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/an3sem1/labSSCMIPS/MMX/MMX.cache/wt [current_project]
set_property parent.project_path E:/an3sem1/labSSCMIPS/MMX/MMX.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/an3sem1/labSSCMIPS/MMX/MMX.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  E:/an3sem1/labSSCMIPS/MMX/MMX.srcs/sources_1/new/adder.vhd
  E:/an3sem1/labSSCMIPS/MMX/MMX.srcs/sources_1/new/adder_32bits.vhd
  E:/an3sem1/labSSCMIPS/MMX/MMX.srcs/sources_1/new/adder_8bits.vhd
  E:/an3sem1/labSSCMIPS/MMX/MMX.srcs/sources_1/new/adder_16bits.vhd
  E:/an3sem1/labSSCMIPS/MMX/MMX.srcs/sources_1/new/REG_FILE.vhd
  E:/an3sem1/labSSCMIPS/MMX/MMX.srcs/sources_1/new/mux15_1.vhd
  E:/an3sem1/labSSCMIPS/MMX/MMX.srcs/sources_1/new/MainControl.vhd
  E:/an3sem1/labSSCMIPS/MMX/MMX.srcs/sources_1/new/alu8.vhd
  E:/an3sem1/labSSCMIPS/MMX/MMX.srcs/sources_1/new/alu64.vhd
  E:/an3sem1/labSSCMIPS/MMX/MMX.srcs/sources_1/new/alu32.vhd
  E:/an3sem1/labSSCMIPS/MMX/MMX.srcs/sources_1/new/alu16.vhd
  E:/an3sem1/labSSCMIPS/MMX/MMX.srcs/sources_1/new/Main.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Main -part xc7k70tfbv676-1


write_checkpoint -force -noxdef Main.dcp

catch { report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb }
